### ISSUE TITLE
Update favicon with OSM US logo

### ISSUE THREAD

**Issue by jessbeutler** [osmus/tasking-manager#122]
Replace favicon with OSM US logo

**Comment by quincylvania** [comment]
The current favicon seems to be correct… 

https://github.com/osmus/tasking-manager/blob/develop/frontend/public/static/favicon.ico

Some browsers like to cache favicons for quite awhile, so perhaps some users are seeing the old one? There is also a whole complex suite of icon formats that different platforms prefer instead of favicon.ico, but this should be fine unless someone notices an issue.
