### ISSUE TITLE
Changeset Comment field in the Edit task page has an unusual starting offeset

### ISSUE THREAD

**Issue by watmildon** [osmus/tasking-manager#265]
Not quite sure what's happening here.

![image](https://user-images.githubusercontent.com/118567155/220482238-b5823ca0-fba0-4fc4-a0b6-6bb544ecfb4c.png)

**Comment by watmildon** [comment]
Hmmm... on another project I see this:
![image](https://user-images.githubusercontent.com/118567155/220482358-2ed5752e-8ded-438a-ae06-c4f2fe2e9371.png)

So either I need the project number in the above one or I shouldn't be seeing it here? Not sure.

**Comment by quincylvania** [comment]
Okay, there was a missing environment variable on the new server. This should be `#osmus-tasks-381`. Fixed in https://github.com/osmus/tasking-manager/commit/b8f100e50e4804e657b4a9fd079ed552cf68d722.

The extra spacing is just hacky padding that TM adds to fit the default comment token. It looks weird when the token is too short.

**Comment by watmildon** [comment]
The first one was from an older project and the second from a branch new project. Presumably the default tag just isn't populated for the older project.
